services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tests\Behat\:
        resource: '../tests/Behat/*'

    Tests\DataFixtures\:
        resource: '../tests/DataFixtures/*'

    Tests\DataFixtures\LoadTemplate:
        class: Tests\DataFixtures\LoadTemplate
        calls:
            - setParams: ['@parameter_bag']

    Tests\DataFixtures\LoadConfig:
        class: Tests\DataFixtures\LoadConfig
        calls:
            - setParams: ['@parameter_bag']
